- name: Gathering existing lv's on {{vgname}}
  shell: lvs {{ vgname }} --noheadings -o lv_name | sed 's/^ *//g'
  register: existing_lvs
 

- name: Deleting lv's
  lvol:
    vg: "{{ vgname }}"
    lv: "{{ item }}"
    state: absent
    force: yes
  with_items:
    - "{{ existing_lvs.stdout_lines | map('trim') | list }}"

- name: Deleting {{ vgname }} volume group
  lvg:
    vg: "{{ vgname }}"
    state: absent